### ISSUE TITLE
feat(tests): write API level boundary tests for `ConfigDefinition`

### ISSUE THREAD

**Issue by niyasrad** [qreater/Tartarus#13]
## Description

- [ ] Bug Report
- [x] Feature Request

## Details

- **Feature Description:**  There can be a lot of boundary tests for each functionality, that can be tested, for improving test coverage.
    - The testing kit will have `unit_tests` - a folder, which will in-turn have `feature_name` - e.g. `config_definition` as a folder, and it will have the following tests.
    - Test suites will be present for `CRUDL` operations, with each letter having it's own file. `test_create.py` - and so on.
    - We will start this procedure with `config_definition`

**Comment by Vaish24navi** [comment]
Closed with #14
