### ISSUE TITLE
feat(setup): re-design for directory structure

### ISSUE THREAD

**Issue by niyasrad** [qreater/Tartarus#15]
## Description
The current folder structure could be modified to be on-par with industry standards

- [ ] Bug Report
- [x] Feature Request

## Details

- **Feature Description:**  Re-Design the folder structure to be on-par with industry standards
    - Move all `.py` extension/`poetry` files into `app`.
    - Ensure repository level configuration files are present inside a particular folder.
    - The existing application must be tested in all levels - local, CI based tests and must pass.

**Comment by Vaish24navi** [comment]
I believe the current folder structure is valid and perfect, and moreover moving the files according to the issue description would create further problems in testing.

But kudos for thinking to keep the directory structure clean @niyasrad! :clinking_glasses:
