### ISSUE TITLE
feat(config): build APIs and tests for configs

### ISSUE THREAD

**Issue by niyasrad** [qreater/Tartarus#17]
## Description

- [x] Feature Request

## Tasks

- [x] #26
- [x] #30
- [x] #38
- [x] #42 
- [x] #40 

## Details

- **Feature Description:**  To have a complete base `v1` API, we will need configs
    - A `config` goes under the `config_definition` - where `config_definition` is the template.
    - Take the standards and folder structure for `config_definition` and replicate the following
        - CRUDL API for `config`
        - Utilities - `validation`, `queries` and `utils`
    - Test the utilities and functions written and ensure all test cases pass.
    - Make sure to write border/edge cases for the utilities

**Comment by Vaish24navi** [comment]
All the tasks for this issue has been completed along with respective sub-issues.

Closing the issue now.
